CREATE TABLE  IF NOT EXISTS PUBLIC.GENRE
(
    GENRE_ID   INTEGER NOT NULL AUTO_INCREMENT primary key,
    GENRE_NAME CHARACTER VARYING(31)
);

INSERT INTO GENRE (GENRE_NAME)
VALUES ('Комедия'), ('Драма');

CREATE TABLE IF NOT EXISTS PUBLIC.MPA
(
    MPA_ID   INTEGER NOT NULL AUTO_INCREMENT primary key,
    MPA_NAME CHARACTER VARYING(7)
);


CREATE TABLE IF NOT EXISTS PUBLIC.FILMS
(
    FILM_ID         INTEGER NOT NULL AUTO_INCREMENT primary key,
    FILM_NAME       CHARACTER VARYING(200),
    DESCRIPTION     CHARACTER VARYING(200),
    MPA_ID          INTEGER references MPA (MPA_ID),
    GENRE_ID        INTEGER references GENRE (GENRE_ID),
    RELEASE_DATE    DATE,
    DURATION_MINUTE INTEGER
);

--INSERT INTO films (FILM_NAME,  DESCRIPTION,  RELEASE_DATE, DURATION_MINUTE)
--VALUES ('testFilm', 'testing', '1989-04-17', 120);

CREATE TABLE IF NOT EXISTS PUBLIC.USERS
(
    USER_ID  INTEGER NOT NULL AUTO_INCREMENT primary key,
    EMAIL    CHARACTER VARYING(63),
    LOGIN    CHARACTER VARYING(63),
    USER_NAME     CHARACTER VARYING(63),
    BIRTHDAY DATE
);

CREATE TABLE IF NOT EXISTS PUBLIC.FRIENDSHIP
(
    USER_ID     INTEGER NOT NULL references USERS (USER_ID),
    FRIEND_ID   INTEGER NOT NULL references USERS (USER_ID)
);


CREATE TABLE IF NOT EXISTS PUBLIC.LIKES_FILM
(
    FILM_ID INTEGER NOT NULL references FILMS(FILM_ID),
    USER_ID INTEGER NOT NULL references USERS(USER_ID)
);
